[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache = true
solc_version = "0.8.20"

remappings = ["solidity-examples/=lib/solidity-examples/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
